version: '3.8'
services:
    webserver:
        build:
          dockerfile: ./nginx/
          context: ./
        image: sciohub/innovation-catalogue-connect:nginx
        container_name: laravel-nginx
        restart: unless-stopped
        volumes:
          - /etc/letsencrypt/live/innovation.dev.api.scio.services/fullchain.pem:/etc/letsencrypt/live/innovation.dev.api.scio.services/fullchain.pem
          - /etc/letsencrypt/live/innovation.dev.api.scio.services/privkey.pem:/etc/letsencrypt/live/innovation.dev.api.scio.services/privkey.pem
        ports:
          - 50100:443
          - 50101:80

    php:
        image: sciohub/innovation-catalogue-connect:dev
        container_name: laravel-app
        restart: unless-stopped